name: sicap-env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - cudatoolkit
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - tqdm
  - openpyxl
  - pillow
  - albumentations
  - pyyaml
